export const resumes = {
  workingExperience: [
    {
      title: 'Fullstack Developer Volunteer',
      location: 'CuraJOY - New York',
      duration: 'Jan 2025 - Present | Full Time',
      responsibilities: [
        'Built React and Node.js microservices on AWS Amplify, scaling throughput by 35% for 3,000+ monthly active users.',
        'Optimized PostgreSQL queries and Redis caching, reducing API latency by 30% and improving global data consistency.',
        'Automated CI/CD pipelines with GitHub Actions, reducing deployment failures by 40% and accelerating release cycles by 25%.',
        'Conducted WCAG/508 accessibility testing, cutting compliance issues 40% and improving user adoption across devices.',
        'Led peer code reviews and regression testing, raising code reliability and reducing defects by 35%.',
      ],
      link: 'https://curajoy.org/',
    },
    {
      title: 'Software Developer Intern',
      location: 'Accenture - Mumbai',
      duration: 'Aug 2022 - Dec 2025 | Internship',
      responsibilities: [
        '        Built Java-based microservices with SQL backends, improving service uptime by 20% and streamlining workflows.',
        'Automated monitoring using Python and Linux CRON jobs, cutting manual workload by 40% and SLA response time.',
        'Integrated REST APIs into cloud apps, reducing sync failures by 25% and increasing API success rates by 30%.',
        'Designed structured logging pipelines, reducing error resolution time by 30% for production support teams.',
      ],
      link: 'https://www.accenture.com/in-en',
    },
    {
      title: 'Software Engineering Intern',
      location: 'Vidyalankar Institute of Technology - Mumbai',
      duration: 'May 2022 - Jul 2022 | Internship',
      responsibilities: [
        'Built real-time dashboards with JavaScript and Firebase, improving accessibility and adoption by 50% across users.',
        'Designed responsive UI components and integrated REST APIs, reducing bug reports by 20% and boosting retention by 30%.',
        'Applied MVC design patterns and modular architecture, reducing integration complexity by 25% for future projects.',
        'Optimized backend queries and caching, improving response speed from 3.2s → 1.8s across multiple endpoints.',
      ],
      link: 'https://vit.edu.in/',
    },
  ],
  voluntaryExperience: [
    {
      title: 'Research Assistant | ML for 2D Material Discovery',
      location: 'Stevens Institute of Technology - Hoboken, New Jersey',
      duration: 'Nov 2024 - June 2025 | Volunteer',
      responsibilities: [
        'Contributed to research on accelerating 2D materials discovery using ML models for electronics, optoelectronics, and quantum computing.',
        'Conducted literature review on deep generative approaches (CDVAE, MTG pipeline, GANs) for TMD characterization.',
        'Identified and evaluated Computational 2D Materials Database (C2DB) as a primary dataset for ML model training.',
        'Analyzed feasibility of ML pipelines (CDVAE, MTG) for generating novel 2D material structures.',
        'Implemented CDVAE locally to generate stable 2D materials, validated with Density Functional Theory (DFT).',
        'Applied computational techniques including Crystal Structure Prediction (CSP) and Phonon Dispersion Analysis.',
        'Tools & Technologies: Python, PyTorch, TensorFlow, C2DB, 2DMatPedia, MC2D, V2DM, DFT',
      ],
      link: 'https://www.stevens.edu/advanced-quantum-materials-lab/',
    },
  ],
  education: [
    {
      institution: 'Stevens Institute of Technology',
      duration: '2023 - 2025',
      degree: 'Masters of Science in Computer Science',
      gpa: '3.71 / 4.00',
      keySubjects: [
        'Data Structures and Algorithms',
        'Cloud Computing',
        'Web Development',
        'Database Management Systems',
      ],
      link: 'https://www.stevens.edu/',
    },
  ],
  additionalSkills: {
    programmingLanguages: [
      'JavaScript',
      'TypeScript',
      'Java',
      'Python',
      'C++',
      'C#',
      'R',
      'PHP',
    ],
    webDevelopment: [
      'React',
      'Next.js',
      'Angular',
      'Redux',
      'Bootstrap',
      'Material UI',
    ],
    mobileDevelopment: [
      'React Native (Working Proficiency)',
      'Cordova (Working Proficiency)',
    ],
    databases: [
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Firebase',
      'DynamoDB',
      'SQLite',
    ],
    cloudAndDevOps: [
      'AWS (Amplify, Lambda, S3, DynamoDB, EC2)',
      'Docker',
      'Kubernetes',
      'GitHub Actions',
      'Jenkins',
    ],
    testingAndQA: [
      'Jest',
      'React Testing Library',
      'JUnit',
      'Mockito',
      'TDD',
      'Accessibility (WCAG 508)',
    ],
    tools: ['Git', 'JIRA', 'Confluence', 'Figma', 'Linux CLI'],
    languages: [
      'English (Bilingual Proficiency)',
      'Hindi (Fluent)',
      'Marathi (Native)',
    ],
    interests: ['Badminton', 'Swimming', 'Traveling', 'Movies', 'Music'],
  },
}
